spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spec_criteria_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: create